In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
from sklearn import linear_model as lm

In [2]:
x_1 = np.random.uniform(10,40,100)
x_2 = np.random.uniform(-50,20,100)
x_3 = np.random.uniform(20,60,100)
x_4 = np.random.uniform(10,40,100)
x_5 = np.random.uniform(-50,20,100)
x_6 = np.random.uniform(20,60,100)
epsilon = np.random.normal(0,10,100)

In [3]:
y=-30+1.3*x_1+1.6*x_2+1.1*x_3+0.7*x_4-2.1*x_5-0.9*x_6+epsilon

In [4]:
X_ols=pd.DataFrame()
X_ols['Constant']=pd.Series(np.ones(100))
X_ols['X1'] = pd.Series(x_1)
X_ols['X2'] = pd.Series(x_2)
X_ols['X3'] = pd.Series(x_3)
X_ols['X4'] = pd.Series(x_4)
X_ols['X5'] = pd.Series(x_5)
X_ols['X6'] = pd.Series(x_6)

In [5]:
model_reg = sm.OLS(y,X_ols).fit()
model_reg.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.978
Model:                            OLS   Adj. R-squared:                  0.977
Method:                 Least Squares   F-statistic:                     704.8
Date:                Mon, 30 Sep 2024   Prob (F-statistic):           3.31e-75
Time:                        12:44:05   Log-Likelihood:                -356.27
No. Observations:                 100   AIC:                             726.5
Df Residuals:                      93   BIC:                             744.8
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Constant     -19.4298      6.745     -2.881      0.005     -32.824      -6.036
X1             1.1116      0.109     10.220      0.000       0.896       1.328
X2             1.5529      0.045     34.515      0.000       1.464       1.642
X3             1.0891      0.076     14.270      0.000       0.938       1.241
X4             0.6399      0.108      5.922      0.000       0.425       0.854
X5            -2.0851      0.044    -47.439      0.000      -2.172      -1.998
X6            -1.0034      0.085    -11.811      0.000      -1.172      -0.835
==============================================================================
Omnibus:                        1.207   Durbin-Watson:                   1.987
Prob(Omnibus):                  0.547   Jarque-Bera (JB):                1.091
Skew:                          -0.070   Prob(JB):                        0.580
Kurtosis:                       2.508   Cond. No.                         564.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [6]:
# Now we add some unrelated coefficients
x_7 = np.random.uniform(10,40,100)
x_8 = np.random.uniform(-50,20,100)
x_9 = np.random.uniform(20,60,100)
x_10 = np.random.uniform(10,40,100)
x_11 = np.random.uniform(-50,20,100)
x_12 = np.random.uniform(20,60,100)

In [7]:
X_ext = pd.DataFrame()
X_ext['Constant']=pd.Series(np.ones(100))
X_ext['X1'] = pd.Series(x_1)
X_ext['X2'] = pd.Series(x_2)
X_ext['X3'] = pd.Series(x_3)
X_ext['X4'] = pd.Series(x_4)
X_ext['X5'] = pd.Series(x_5)
X_ext['X6'] = pd.Series(x_6)
X_ext['X7'] = pd.Series(x_7)
X_ext['X8'] = pd.Series(x_8)
X_ext['X9'] = pd.Series(x_9)
X_ext['X10'] = pd.Series(x_10)
X_ext['X11'] = pd.Series(x_11)
X_ext['X12'] = pd.Series(x_12)

In [8]:
model_reg = sm.OLS(y,X_ext).fit()
model_reg.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.979
Model:                            OLS   Adj. R-squared:                  0.977
Method:                 Least Squares   F-statistic:                     344.5
Date:                Mon, 30 Sep 2024   Prob (F-statistic):           7.56e-68
Time:                        12:46:13   Log-Likelihood:                -354.13
No. Observations:                 100   AIC:                             734.3
Df Residuals:                      87   BIC:                             768.1
Df Model:                          12                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Constant     -17.5479      8.875     -1.977      0.051     -35.188       0.092
X1             1.0894      0.113      9.604      0.000       0.864       1.315
X2             1.5573      0.046     33.829      0.000       1.466       1.649
X3             1.0878      0.081     13.469      0.000       0.927       1.248
X4             0.6321      0.114      5.540      0.000       0.405       0.859
X5            -2.0956      0.046    -45.542      0.000      -2.187      -2.004
X6            -1.0162      0.088    -11.498      0.000      -1.192      -0.841
X7            -0.0011      0.105     -0.011      0.991      -0.210       0.207
X8             0.0690      0.044      1.561      0.122      -0.019       0.157
X9            -0.0026      0.085     -0.030      0.976      -0.172       0.166
X10            0.0697      0.108      0.644      0.521      -0.145       0.285
X11           -0.0245      0.044     -0.561      0.576      -0.111       0.062
X12           -0.0353      0.084     -0.419      0.676      -0.203       0.132
==============================================================================
Omnibus:                        1.612   Durbin-Watson:                   2.027
Prob(Omnibus):                  0.447   Jarque-Bera (JB):                1.262
Skew:                           0.018   Prob(JB):                        0.532
Kurtosis:                       2.451   Cond. No.                     1.02e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.02e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [9]:
# When we input the matrix, we don't need to add the column of ones because \
# Lasso automatically takes it into account

X_ext = X_ext.drop(columns=['Constant'])
model_lasso = lm.Lasso(alpha=1).fit(X_ext,y)
model_lasso.coef_

array([ 1.07870292,  1.55540884,  1.08042733,  0.61448547, -2.09160485,
       -1.00906495,  0.        ,  0.06816391, -0.        ,  0.05489861,
       -0.02077121, -0.02652208])

In [15]:
model_lasso = lm.Lasso(alpha=100).fit(X_ext,y)
model_lasso.coef_

array([ 0.        ,  1.31109017,  0.45878641,  0.        , -1.85738252,
       -0.54822706,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ])

In [16]:
# We now apply Ridge Regression to our data

model_ridge = lm.Ridge(alpha=10).fit(X_ext,y)
model_ridge.coef_

array([ 1.08805102e+00,  1.55695821e+00,  1.08702547e+00,  6.30910755e-01,
       -2.09501288e+00, -1.01580875e+00, -1.07025952e-03,  6.90205281e-02,
       -2.26722601e-03,  6.95047189e-02, -2.43468474e-02, -3.51514500e-02])

In [19]:
model_ridge = lm.Ridge(alpha=10000).fit(X_ext,y)
model_ridge.coef_

array([ 0.5196876 ,  1.24196791,  0.62457542,  0.20993741, -1.67511097,
       -0.71183182,  0.01149689,  0.06175776,  0.10580474, -0.0185427 ,
        0.03599376,  0.0221109 ])